server:
  httpPort: 9094

logger:
  file: /tmp/blues/blueblog/blueblog-job.log
  level: debug

language:
  local: "zh-cn"

redis:
  addr: "127.0.0.1:8901"
  db: "0"
  maxRetries: 3
  minIdleConns: 5
  pass: "Root1234"
  poolSize: 10

mysql:
  base:
    maxOpenConn: 10
    maxIdleConn: 60
    connMaxLifeTime: 60
  read:
    addr: "127.0.0.1:8306"
    name: "go_advanced_tc"
    pass: "Root1234"
    user: "root"
  write:
    addr: "127.0.0.1:8306"
    name: "go_advanced_tc"
    pass: "Root1234"
    user: "root"

rabbitmq:
  url: "amqp://root:Root1234@127.0.0.1:8902/"

