server:
  httpPort: 9091

blues:
  blueblog:
    service:
      addr: "127.0.0.1:9093"

logger:
  file: /tmp/blues/blueblog/blueblog-interface.log
  level: debug

language:
  local: "zh-cn"

redis:
  addr: "127.0.0.1:8901"
  db: "0"
  maxRetries: 3
  minIdleConns: 5
  pass: "Root1234"
  poolSize: 10
