server:
  httpPort: 9092
  grpcPort: 9093

logger:
  file: /tmp/blues/blueblog/blueblog-service.log
  level: debug

language:
  local: "zh-cn"

redis:
  addr: "10.69.77.221:8901"
  db: "0"
  maxRetries: 3
  minIdleConns: 5
  pass: "Root1234"
  poolSize: 10

mysql:
  base:
    maxOpenConn: 10
    maxIdleConn: 60
    connMaxLifeTime: 60
  read:
    addr: "10.69.77.221:8306"
    name: "go_advanced_tc"
    pass: "Root1234"
    user: "root"
  write:
    addr: "10.69.77.221:8306"
    name: "go_advanced_tc"
    pass: "Root1234"
    user: "root"
